// react-app/src/App.js
import React, { Component } from 'react';
import './App.css';
import Textfield from './Textfield';

class App extends Component {

  constructor(props) {
    super(props);
    this.state = {
      firstName: 'Shripal',
      lastName: 'Soni'
    };
  }

  handleFirstNameChange = (event) => {
    this.setState({
      firstName: event.detail
    })
  }

  handleLastNameChange = (event) => {
    this.setState({
      lastName: event.detail
    })
  }

  render() {
    const { firstName, lastName } = this.state;

    return (
      <div className="web-components-container">
        <h1>React Stencil Web Component</h1>
        <div className="comp">
          <h2>Hello World Component</h2>
          <sh-hello-world 
            first={firstName} 
            last={lastName}>
          </sh-hello-world>
        </div>
        <div className="comp">
          <h2>Textfield Component</h2>
          <Textfield
            config={{a: '1', b: '2'}}
            testArray={[1,2,3]}
            label="First Name"
            placeholder="Enter First Name"
            value={firstName}
            isRequired={false}
            maxlength="10"
            onChange={this.handleFirstNameChange} />
          <Textfield
            label="Last Name"
            placeholder="Enter Last Name"
            value={lastName}
            isRequired={true}
            maxlength="20"
            extraProp="10"
            onChange={this.handleLastNameChange} />
        </div>
      </div>
    );
  }
}

export default App;

// angular-app/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'Stencil Web Components Usage App';

  firstName = 'Shripal';

  lastName = 'Soni';

  showHelloWorld = true;
}

<div style="text-align:center">
  <h1>
    Welcome to {{ title }}!
  </h1>
  <img width="300" alt="Angular Logo" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNTAgMjUwIj4KICAgIDxwYXRoIGZpbGw9IiNERDAwMzEiIGQ9Ik0xMjUgMzBMMzEuOSA2My4ybDE0LjIgMTIzLjFMMTI1IDIzMGw3OC45LTQzLjcgMTQuMi0xMjMuMXoiIC8+CiAgICA8cGF0aCBmaWxsPSIjQzMwMDJGIiBkPSJNMTI1IDMwdjIyLjItLjFWMjMwbDc4LjktNDMuNyAxNC4yLTEyMy4xTDEyNSAzMHoiIC8+CiAgICA8cGF0aCAgZmlsbD0iI0ZGRkZGRiIgZD0iTTEyNSA1Mi4xTDY2LjggMTgyLjZoMjEuN2wxMS43LTI5LjJoNDkuNGwxMS43IDI5LjJIMTgzTDEyNSA1Mi4xem0xNyA4My4zaC0zNGwxNy00MC45IDE3IDQwLjl6IiAvPgogIDwvc3ZnPg==">
</div>
<div class="comp" *ngIf="showHelloWorld">
  <h2>Hello World Component</h2>
  <sh-hello-world [first]="firstName" [last]="lastName"></sh-hello-world>
</div>
<div class="comp">
  <h2>Textfield Component</h2>
  <sh-textfield
    label="First Name"
    placeholder="Enter First Name"
    [isRequired]="false"
    maxlength="20"
    [value]="firstName"
    [config]="{a: '1', b: '2'}"
    [testArray]="[1, 2, 3]"
    (change)="firstName = $event.detail">
  </sh-textfield>
  <sh-textfield
    label="Last Name"
    placeholder="Enter Last Name"
    [isRequired]="false"
    maxlength="20"
    [value]="lastName"
    (change)="lastName = $event.detail">
  </sh-textfield>
  <!-- <button type="button" (click)="showHelloWorld = !showHelloWorld">Toggle Hello World</button> -->
</div>
